In [3]:
import pandas as pd
import numpy as np

Numpy Overview
---
NumPy provides an extension package for multi-dimensional arrays. It works closer to the hardware (for efficiency) and is designed for scientific computation. Newcomers to NumPy often wondered what the fuss is about.

This lab will help us understand how regular Python arrays perform compared to NumPy arrays. Use the 
timeit
 module to evaluate their performance difference. Create a regular Python array of 1000 integers -

In [11]:
myArray = range(1000)

Then using a comprehension list raise each element to the power of 2.

In [12]:
[x ** 2 for x in myArray]

[0,
 1,
 4,
 9,
 16,
 25,
 36,
 49,
 64,
 81,
 100,
 121,
 144,
 169,
 196,
 225,
 256,
 289,
 324,
 361,
 400,
 441,
 484,
 529,
 576,
 625,
 676,
 729,
 784,
 841,
 900,
 961,
 1024,
 1089,
 1156,
 1225,
 1296,
 1369,
 1444,
 1521,
 1600,
 1681,
 1764,
 1849,
 1936,
 2025,
 2116,
 2209,
 2304,
 2401,
 2500,
 2601,
 2704,
 2809,
 2916,
 3025,
 3136,
 3249,
 3364,
 3481,
 3600,
 3721,
 3844,
 3969,
 4096,
 4225,
 4356,
 4489,
 4624,
 4761,
 4900,
 5041,
 5184,
 5329,
 5476,
 5625,
 5776,
 5929,
 6084,
 6241,
 6400,
 6561,
 6724,
 6889,
 7056,
 7225,
 7396,
 7569,
 7744,
 7921,
 8100,
 8281,
 8464,
 8649,
 8836,
 9025,
 9216,
 9409,
 9604,
 9801,
 10000,
 10201,
 10404,
 10609,
 10816,
 11025,
 11236,
 11449,
 11664,
 11881,
 12100,
 12321,
 12544,
 12769,
 12996,
 13225,
 13456,
 13689,
 13924,
 14161,
 14400,
 14641,
 14884,
 15129,
 15376,
 15625,
 15876,
 16129,
 16384,
 16641,
 16900,
 17161,
 17424,
 17689,
 17956,
 18225,
 18496,
 18769,
 19044,
 19321,
 19600,
 19881,
 20164,
 2

You can time this using Jupyter/IPython magics:

In [13]:
%timeit [x ** 2 for x in myArray]

246 µs ± 17.2 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


Or using the regular timeit() function:

In [14]:
import timeit
print(timeit.timeit(setup='myArray = range(1000)', stmt='[x ** 2 for x in myArray]', number=1000))

0.2744225000000142


Time this against a NumPy array, using:

In [19]:
otherArray = np.arange(1000)

Then time the following operation on our NumPy array:

In [20]:
otherArray ** 2

array([     0,      1,      4,      9,     16,     25,     36,     49,
           64,     81,    100,    121,    144,    169,    196,    225,
          256,    289,    324,    361,    400,    441,    484,    529,
          576,    625,    676,    729,    784,    841,    900,    961,
         1024,   1089,   1156,   1225,   1296,   1369,   1444,   1521,
         1600,   1681,   1764,   1849,   1936,   2025,   2116,   2209,
         2304,   2401,   2500,   2601,   2704,   2809,   2916,   3025,
         3136,   3249,   3364,   3481,   3600,   3721,   3844,   3969,
         4096,   4225,   4356,   4489,   4624,   4761,   4900,   5041,
         5184,   5329,   5476,   5625,   5776,   5929,   6084,   6241,
         6400,   6561,   6724,   6889,   7056,   7225,   7396,   7569,
         7744,   7921,   8100,   8281,   8464,   8649,   8836,   9025,
         9216,   9409,   9604,   9801,  10000,  10201,  10404,  10609,
        10816,  11025,  11236,  11449,  11664,  11881,  12100,  12321,
      

Numpy Data Types and Arrays
---


There's a lot of data out there to process. But before we can crunch the data, we have to munch the data first. This lab will help you learn how to read in data from an external source into our Python application. Download this CSV file of historical data of Apple shares. It contains the dates of the trades, the Open, High, Low, Close, Adj Close prices of Apple stock each day for 2017, and its traded volume. An adjusted closing price (Adj Close) is a stock's closing price on any given day of trading that has been amended to include any distributions and corporate actions that occurred at any time before the next day's open.

We want to read these columns (except the date) into a NumPy array for later data processing and visualization. The following short example will help you get started:


In [41]:
import csv

def openCSV(filename):
    with open(filename, newline='') as f:
        reader = csv.DictReader(f)
        records = np.empty((0,6))

        for row in reader:
            oneRow = np.array([[row['Open'], row['High'], row['Low'], row['Close'], row['Adj Close'], row['Volume']]])
            records = np.append(records, oneRow, axis=0)
    
    return records.astype('float64')

In [55]:
print(records.shape)

NameError: name 'records' is not defined

Using this as a guide, read in the Open, High, Low, Close, Adj Close and Volume for your stock into a 2-dimensional NumPy array. Ignore the Date column for this lab. Be sure to create an empty array (using 
empty()
) with the right dimension and the right data type. When you have internalized the data into your NumPy array, verify it using 
ndim()
, 
shape()
 and display the contents of the array.

## Problem with data type mismatch 
In the notes, an example used 
arange()
 where the 
start
, 
step
 and 
stop
 arguments are floating-point numbers, but the 
dtype
 specifies an int type:

In [140]:
a5 = np.arange(0.5, 5.8, 0.5, int)
print(a5) #[ 0  1  2  3  4  5  6  7  8  9 10]

[ 0  1  2  3  4  5  6  7  8  9 10]


The unexpected result is because for floating-point numbers, the length of the result is 
ceil(stop-start)/step
. Because of floating-point overflow, this rule may result in the last elements being greater than 
stop
. More information can be found here - https://docs.scipy.org/doc/numpy-1.10.1/reference/generated/numpy.arange.html. Note how it says, "When using a non-integer step, such as 0.1, the results will often not be consistent". So _caveat emptor_ - beware when you mix types when using 
arange()
.
*Why does the 
shape
 property show only one dimension?* 
Given the following statements:

In [142]:
a = np.array([1,2,3,4])
print (a.shape) # (4,)

(4,)


Why does 
shape()
 show 
(4,)
? This is because NumPy can only tell the shape of an array if it is a two dimension array, and the shape of an array is a tuple of its dimensions. So an array with one dimension has a shape of 
(n,)
, and a two dimension array has a shape of 
(n,m)
, and a three dimension array has a 
shape
 of 
(n,m,k)
, and so on. However, the
numpy.array([1,2,3,4])
 is a one dimension array and so, 
shape()
 returns a single valued tuple. You can specify a two dimension array like this:

In [143]:
a = np.array([[1,2,3,4]])  # Note extra pair of square-brackets
print (a.shape) # (1,4)

(1, 4)


You can also check the number of dimensions using 
ndim()
:

In [145]:
a = np.array([1,2,3,4])
print (a.ndim) # 1

1


Operations on Arrays
---

Continuing from our earlier exercise to read-in a set of stock prices and traded volumes for Apple stock for 2017 into a NumPy array, this exercise will help you practice the use of several NumPy array operations. Download this CSV file of Apple stock prices for another year - 2016. Check the number of rows in this file. The number of trading days may differ from year to year. If the number of rows for this year is different from your previous year's download, just trim the longer one to make them both the same length. If you wish, you can scan both years for the odd days and remove them, but for this exercise, just pick any random row or rows to delete. This is trivial case but useful one of cleaning up the data in the Data Science ETL process (Extract, Transformation and Load). When you're done, read in the new stock prices and volume traded into another NumPy array, and carry out the following operations:

In [44]:
r17 = openCSV('AAPL-2017.csv')
r16 = openCSV('AAPL-2016.csv')
print("No. of rows: {}".format(records_2016.shape[0]))

No. of rows: 250


In [45]:
if(r16.shape[0] > r17.shape[0]):
    r16 = r16[:-(r16.shape[0] - r17.shape[0]), :]
elif(r16.shape[0] < r17.shape[0]):
    r17 = r17[:-(r17.shape[0] - r16.shape[0]), :]

print('records_2016: {}\nrecords_2017: {}'.format(r16.shape[0], r17.shape[0]))

records_2016: 250
records_2017: 250


1. NumPy lets you sum up the columns of an array. For example, to sum up myArray, you would say myArray.sum(axis=0)

Setting the axis to 0, tells it to iterate and sum down the rows. Setting the axis to 1 tells NumPy to sum across the columns. Using the correct axis, sum the columns for both your arrays, and display the total volume traded for both years. Also calculate and print the change in the traded volume from 2017 to 2016.

In [46]:
r16_rows_sum = r16.sum(axis=0)
r16_rows_sum

r16_cols_sum = records_2016.sum(axis=1)
r16_cols_sum

array([6.76499156e+07, 5.57915145e+07, 6.84578993e+07, 8.10948835e+07,
       7.07984837e+07, 4.97398877e+07, 4.91546952e+07, 6.24400889e+07,
       6.31705884e+07, 7.90104789e+07, 5.30881812e+07, 7.23348756e+07,
       5.21619778e+07, 6.58009964e+07, 5.17949963e+07, 7.50774940e+07,
       1.33370168e+08, 5.56792643e+07, 6.44169765e+07, 4.09439768e+07,
       3.73576701e+07, 4.59647740e+07, 4.64721774e+07, 4.64185711e+07,
       5.40218678e+07, 4.43316701e+07, 4.23440709e+07, 5.00751645e+07,
       4.03518656e+07, 4.90583756e+07, 4.48636830e+07, 3.90214822e+07,
       3.53746765e+07, 3.42812787e+07, 3.19430728e+07, 3.62561717e+07,
       2.75831774e+07, 2.89915815e+07, 3.52167810e+07, 5.04075926e+07,
       3.31700982e+07, 3.69562014e+07, 4.60556091e+07, 3.58294055e+07,
       3.15624007e+07, 2.72022011e+07, 3.35141018e+07, 2.74087061e+07,
       2.50766072e+07, 4.00682177e+07, 3.83040229e+07, 3.44212240e+07,
       4.42057253e+07, 3.55032260e+07, 3.24449266e+07, 2.57040271e+07,
      

In [47]:
r17_rows_sum = r17.sum(axis=0)
r17_rows_sum

r17_cols_sum = r17.sum(axis=1)
r17_cols_sum

array([2.87824761e+07, 2.11186770e+07, 2.21941787e+07, 3.17524840e+07,
       3.35624901e+07, 2.44626915e+07, 2.75891935e+07, 2.70867917e+07,
       2.61124924e+07, 3.44403936e+07, 2.37135970e+07, 2.55978952e+07,
       3.25984974e+07, 2.20507975e+07, 2.32115959e+07, 3.23782033e+07,
       2.63382063e+07, 2.05635067e+07, 3.03781032e+07, 4.92016026e+07,
       1.11985639e+08, 3.37110387e+07, 2.45079403e+07, 2.68465456e+07,
       3.81844526e+07, 2.30047553e+07, 2.83505570e+07, 2.00661587e+07,
       2.30360632e+07, 3.32268688e+07, 3.56237743e+07, 2.25852740e+07,
       2.21988744e+07, 2.45078792e+07, 2.08375808e+07, 2.07888811e+07,
       2.17772781e+07, 2.02580816e+07, 2.34835821e+07, 3.64152920e+07,
       2.62116938e+07, 2.11087936e+07, 2.17506932e+07, 1.74469937e+07,
       1.87078924e+07, 2.21565888e+07, 1.96134924e+07, 1.74223923e+07,
       1.53097926e+07, 2.56924969e+07, 1.92327002e+07, 4.38856987e+07,
       2.15427018e+07, 3.95306011e+07, 2.58609008e+07, 2.03470021e+07,
      

In [49]:
#volume diff
r16_rows_sum[5] - r17_rows_sum[5]

2850453900.0

2. Subtract the respective columns of both NumPy arrays and store the results into a new array called 
change
. Then sum up the columns of this array and display just the volume traded. Verify the result 
- it should be the same as the difference you calculated in the previous step.

In [51]:
change = r16 - r17
change

array([[-1.3190002e+01, -1.0959999e+01, -1.2760002e+01, -1.0800004e+01,
        -1.2739403e+01,  3.8867500e+07],
       [-1.0099998e+01, -1.0660004e+01, -1.3339996e+01, -1.3309998e+01,
        -1.5125732e+01,  3.4672900e+07],
       [-1.5360000e+01, -1.4489998e+01, -1.5939995e+01, -1.5910004e+01,
        -1.7612991e+01,  4.6263800e+07],
       ...,
       [-5.5210007e+01, -5.4950004e+01, -5.4089997e+01, -5.4050010e+01,
        -5.5259506e+01, -1.8936000e+07],
       [-5.3580009e+01, -5.2979996e+01, -5.3220009e+01, -5.3340004e+01,
        -5.4569153e+01, -3.2013000e+06],
       [-5.3480003e+01, -5.3830009e+01, -5.4279999e+01, -5.4320000e+01,
        -5.5530205e+01,  4.4257000e+06]])

In [52]:
change.shape

(250, 6)

In [53]:
# Total vol 
change.sum(axis = 0)[5]

2850453900.0

In [54]:
change[1]

array([-1.0099998e+01, -1.0660004e+01, -1.3339996e+01, -1.3309998e+01,
       -1.5125732e+01,  3.4672900e+07])

3. mPrint one of your arrays, say the 
change
 array. Do you find the default exponential format raggedy and hard to read? You can change this default using
np.set_printoptions(formatter={'float': '{: 6.2f}'.format})
. This tells NumPy to print floating point numbers with 6 spaces for the whole number part and 2 spaces for the fractional part. Note that this change will 'stick', so any subsequent output will be affected. For Jupyter this change is made to the Jupyter server so all subsequent NumPy code will be affected. You can reset the formatter using 
np.set_printoptions()
.

In [71]:
np.set_printoptions(formatter={'float': '{: 6.2f}'.format})
change[1]

array([-10.10, -10.66, -13.34, -13.31, -15.13,  34672900.00])

In [65]:
np.set_printoptions()
change[1]

array([-1.0099998e+01, -1.0660004e+01, -1.3339996e+01, -1.3309998e+01,
       -1.5125732e+01,  3.4672900e+07])

4. Concatenate the table for 2017 to the end of the table for 2016, and call this new array 
combined_years
.

In [127]:
combined_years = np.concatenate((r16, r17))
combined_years.shape

(500, 6)

5. Save the new array 
combined_years
 to a text file, using 
%10.2f
 to format the prices and a comma (,) as a separator between columns.

In [76]:
np.savetxt('data.csv', combined_years, fmt='%10.2f', delimiter=',')

Numpy Array Indexing and Slicing
---

Using your 2017 or 2016 arrays of historical stock prices and trading volumes, perform the following indexing and slicing operations

1. Retrieve the rows for the month of January as a slice; you can assume that the first 20 rows is for the month of January and call the slice 
january
.

In [79]:
jan = r16[:20]
jan

array([[ 102.61,  105.37,  102.00,  105.35,  100.27,  67649400.00],
       [ 105.75,  105.85,  102.41,  102.71,  97.76,  55791000.00],
       [ 100.56,  102.37,  99.87,  100.70,  95.85,  68457400.00],
       [ 98.68,  100.13,  96.43,  96.45,  91.80,  81094400.00],
       [ 98.55,  99.11,  96.76,  96.96,  92.29,  70798000.00],
       [ 98.97,  99.06,  97.34,  98.53,  93.78,  49739400.00],
       [ 100.55,  100.69,  98.84,  99.96,  95.14,  49154200.00],
       [ 100.32,  101.19,  97.30,  97.39,  92.70,  62439600.00],
       [ 97.96,  100.48,  95.74,  99.52,  94.73,  63170100.00],
       [ 96.20,  97.71,  95.36,  97.13,  92.45,  79010000.00],
       [ 98.41,  98.65,  95.50,  96.66,  92.00,  53087700.00],
       [ 95.10,  98.19,  93.42,  96.79,  92.13,  72334400.00],
       [ 97.06,  97.88,  94.94,  96.30,  91.66,  52161500.00],
       [ 98.63,  101.46,  98.37,  101.42,  96.53,  65800500.00],
       [ 101.52,  101.53,  99.21,  99.44,  94.65,  51794500.00],
       [ 99.93,  100.88,  98.07, 

2. We have a slice, so let's now do the dice. Update the volume for the first row of 
january
 to 100. Is the change reflected in the original array? It should because 
january
 is a slice, meaning it is a view of the original array. Any changes made to the slice will affect the original array.

In [81]:
jan[0][5] = 100
jan

array([[ 102.61,  105.37,  102.00,  105.35,  100.27,  100.00],
       [ 105.75,  105.85,  102.41,  102.71,  97.76,  55791000.00],
       [ 100.56,  102.37,  99.87,  100.70,  95.85,  68457400.00],
       [ 98.68,  100.13,  96.43,  96.45,  91.80,  81094400.00],
       [ 98.55,  99.11,  96.76,  96.96,  92.29,  70798000.00],
       [ 100.00,  100.00,  100.00,  100.00,  100.00,  100.00],
       [ 100.55,  100.69,  98.84,  99.96,  95.14,  49154200.00],
       [ 100.32,  101.19,  97.30,  97.39,  92.70,  62439600.00],
       [ 97.96,  100.48,  95.74,  99.52,  94.73,  63170100.00],
       [ 96.20,  97.71,  95.36,  97.13,  92.45,  79010000.00],
       [ 98.41,  98.65,  95.50,  96.66,  92.00,  53087700.00],
       [ 95.10,  98.19,  93.42,  96.79,  92.13,  72334400.00],
       [ 97.06,  97.88,  94.94,  96.30,  91.66,  52161500.00],
       [ 98.63,  101.46,  98.37,  101.42,  96.53,  65800500.00],
       [ 101.52,  101.53,  99.21,  99.44,  94.65,  51794500.00],
       [ 99.93,  100.88,  98.07,  99.9

3. Print the first 5 rows of the original array (do not print the 
january
 slice). Remember to use 
set_printoptions()
 introduced in the previous exercise to make your output easier to read. Verify that our earlier change to the 
january
 slice has affected the original array - the volume for the first row should be 100

In [83]:
r16[:5]

array([[ 102.61,  105.37,  102.00,  105.35,  100.27,  100.00],
       [ 105.75,  105.85,  102.41,  102.71,  97.76,  55791000.00],
       [ 100.56,  102.37,  99.87,  100.70,  95.85,  68457400.00],
       [ 98.68,  100.13,  96.43,  96.45,  91.80,  81094400.00],
       [ 98.55,  99.11,  96.76,  96.96,  92.29,  70798000.00]])

4. Now we want to find the highest closing price for the year. We can easily do this using the 
max()
 function in NumPy. It returns a tuple of the maximum value for each column. For example

    a = np.array([[9,2], [3,4], [5,6]])
    (x,y) = a.max(axis=0)
    
 This will return 9 and 6 - the largest values for the three rows. Setting the axis parameter to 0 instructs NumPy to scan by the rows (1 tells it scan by the columns). You can verify your result with Excel, using something like 
=MAX(E2:E253)
 in an empty cell, where E2 and 
E253
 are the starting and ending cells for the closing price column. If you are using Jupyter, remember to close Excel before running the application, as the CSV file will be locked otherwise. If Jupyter barfs with opening the CSV file, try restarting the Kernel (you can find it under the Kernel menu in Jupyter). One more gotcha - do not name your tuple 
open
 as it can cause problems with the 
open()
 method. This is also a Jupyter specific problem and should not affect other development or execution environments.

    Experiment with other columns, and also with finding the smallest value using the 
min()
 function.

In [91]:
a = np.array([[9,2], [3,4], [5,6]]) 
(x,y) = a.max(axis=0)
print((x,y))

(9, 6)


In [98]:
# myp = maximum(highest) closing price for the year
(u,v,w,x,y,z) = r16.max(axis=0)
print(x)

myp = r16.max(axis=0)[3] #Dzifs!
print(myp) 

118.25
118.25


5. Finally, vertically slice the High and Low price columns and display just their first 5 rows.

In [151]:
r16[:5 , 1:3]

array([[ 105.37,  102.00],
       [ 105.85,  102.41],
       [ 102.37,  99.87],
       [ 100.13,  96.43],
       [ 99.11,  96.76]])

Broadcasting
---

Using your 2017 or 2016 array of historical stock prices and trading volumes, let's try broadcasting to our NumPy array.

Let's imagine that you want to project the Open and Close prices into the future. To do this, increase all the values in the Open column by 10% and the Close column by 20%. This is something we can easily do with NumPy arrays using a broadcast, but with considerable effort with regular Python arrays. All we have to do is first slice the columns for the Open and Close columns - call this new NumPy array 
projection
. Then create a broadcast array with the change factors (1.1 and 1.2) which we then multiply with the 
projection
 array. To keep the output manageable, you should display just the first 5 rows of the 
projection
 array before and after broadcasting.

In [148]:
# projection = "open" and "close" columns aka Numpy array projection
# [row['Open'], row['High'], row['Low'], row['Close'], row['Adj Close'], row['Volume']]
projection = r16[:, ::3]
projection

array([[ 136.57,  140.22],
       [ 182.74,  177.48],
       [ 100.56,  100.70],
       [ 98.68,  96.45],
       [ 98.55,  96.96],
       [ 100.00,  100.00],
       [ 100.55,  99.96],
       [ 100.32,  97.39],
       [ 97.96,  99.52],
       [ 96.20,  97.13],
       [ 98.41,  96.66],
       [ 95.10,  96.79],
       [ 97.06,  96.30],
       [ 98.63,  101.42],
       [ 101.52,  99.44],
       [ 99.93,  99.99],
       [ 96.04,  93.42],
       [ 93.79,  94.09],
       [ 94.79,  97.34],
       [ 96.47,  96.43],
       [ 95.42,  94.48],
       [ 95.00,  96.35],
       [ 95.86,  96.60],
       [ 96.52,  94.02],
       [ 93.13,  95.01],
       [ 94.29,  94.99],
       [ 95.92,  94.27],
       [ 93.79,  93.70],
       [ 94.19,  93.99],
       [ 95.02,  96.64],
       [ 96.67,  98.12],
       [ 98.84,  96.26],
       [ 96.00,  96.04],
       [ 96.31,  96.88],
       [ 96.40,  94.69],
       [ 93.98,  96.10],
       [ 96.05,  96.76],
       [ 97.20,  96.91],
       [ 96.86,  96.69],
       [ 97.6

In [147]:
projection = r16[:, 0:6:3]
projection

array([[ 136.57,  140.22],
       [ 182.74,  177.48],
       [ 100.56,  100.70],
       [ 98.68,  96.45],
       [ 98.55,  96.96],
       [ 100.00,  100.00],
       [ 100.55,  99.96],
       [ 100.32,  97.39],
       [ 97.96,  99.52],
       [ 96.20,  97.13],
       [ 98.41,  96.66],
       [ 95.10,  96.79],
       [ 97.06,  96.30],
       [ 98.63,  101.42],
       [ 101.52,  99.44],
       [ 99.93,  99.99],
       [ 96.04,  93.42],
       [ 93.79,  94.09],
       [ 94.79,  97.34],
       [ 96.47,  96.43],
       [ 95.42,  94.48],
       [ 95.00,  96.35],
       [ 95.86,  96.60],
       [ 96.52,  94.02],
       [ 93.13,  95.01],
       [ 94.29,  94.99],
       [ 95.92,  94.27],
       [ 93.79,  93.70],
       [ 94.19,  93.99],
       [ 95.02,  96.64],
       [ 96.67,  98.12],
       [ 98.84,  96.26],
       [ 96.00,  96.04],
       [ 96.31,  96.88],
       [ 96.40,  94.69],
       [ 93.98,  96.10],
       [ 96.05,  96.76],
       [ 97.20,  96.91],
       [ 96.86,  96.69],
       [ 97.6

In [125]:
projection = r16[:, [0,3]]
projection

array([[ 102.61,  105.35],
       [ 105.75,  102.71],
       [ 100.56,  100.70],
       [ 98.68,  96.45],
       [ 98.55,  96.96],
       [ 100.00,  100.00],
       [ 100.55,  99.96],
       [ 100.32,  97.39],
       [ 97.96,  99.52],
       [ 96.20,  97.13],
       [ 98.41,  96.66],
       [ 95.10,  96.79],
       [ 97.06,  96.30],
       [ 98.63,  101.42],
       [ 101.52,  99.44],
       [ 99.93,  99.99],
       [ 96.04,  93.42],
       [ 93.79,  94.09],
       [ 94.79,  97.34],
       [ 96.47,  96.43],
       [ 95.42,  94.48],
       [ 95.00,  96.35],
       [ 95.86,  96.60],
       [ 96.52,  94.02],
       [ 93.13,  95.01],
       [ 94.29,  94.99],
       [ 95.92,  94.27],
       [ 93.79,  93.70],
       [ 94.19,  93.99],
       [ 95.02,  96.64],
       [ 96.67,  98.12],
       [ 98.84,  96.26],
       [ 96.00,  96.04],
       [ 96.31,  96.88],
       [ 96.40,  94.69],
       [ 93.98,  96.10],
       [ 96.05,  96.76],
       [ 97.20,  96.91],
       [ 96.86,  96.69],
       [ 97.6

In [141]:
broadcast1 = projection[:5,::3][0] * 1.1

broadcast1

array([ 150.23])

In [137]:
broadcast2 = projection[1] * 1.2

broadcast2

array([ 219.28,  212.98])

In [146]:
projection

array([[ 136.57,  140.22],
       [ 182.74,  177.48],
       [ 100.56,  100.70],
       [ 98.68,  96.45],
       [ 98.55,  96.96],
       [ 100.00,  100.00],
       [ 100.55,  99.96],
       [ 100.32,  97.39],
       [ 97.96,  99.52],
       [ 96.20,  97.13],
       [ 98.41,  96.66],
       [ 95.10,  96.79],
       [ 97.06,  96.30],
       [ 98.63,  101.42],
       [ 101.52,  99.44],
       [ 99.93,  99.99],
       [ 96.04,  93.42],
       [ 93.79,  94.09],
       [ 94.79,  97.34],
       [ 96.47,  96.43],
       [ 95.42,  94.48],
       [ 95.00,  96.35],
       [ 95.86,  96.60],
       [ 96.52,  94.02],
       [ 93.13,  95.01],
       [ 94.29,  94.99],
       [ 95.92,  94.27],
       [ 93.79,  93.70],
       [ 94.19,  93.99],
       [ 95.02,  96.64],
       [ 96.67,  98.12],
       [ 98.84,  96.26],
       [ 96.00,  96.04],
       [ 96.31,  96.88],
       [ 96.40,  94.69],
       [ 93.98,  96.10],
       [ 96.05,  96.76],
       [ 97.20,  96.91],
       [ 96.86,  96.69],
       [ 97.6